# * 💁 If problems with the linker, try this:

# [target.aarch64-apple-darwin]
# linker = "clang"
# rustflags = [
#   "-C", "link-arg=-fuse-ld=lld",
#   "--cfg", "erase_components"
# ]

# [target.x86_64-unknown-linux-musl]
# linker = "musl-gcc"
# rustflags = [
#     "-C", "target-feature=+crt-static",
#     "-C", "link-arg=-v"
# ]